app/accounts/urls.py
from django.urls import path

from . import views


app_name = 'accounts'

urlpatterns = [
   path('sign-up/', views.SignUpView.as_view(), name='sign-up'),
   path('sign-in/', views.SignInView.as_view(), name='sign-in'),
   path('logout/', views.logout_view, name='logout'),
]

app/chat/urls.py
from django.urls import path, re_path

from . import views


app_name = 'chat'

urlpatterns = [
   path('threads/', views.ThreadListView.as_view(), name='thread-list'),
   path('thread/<int:thread_id>/', views.ThreadDetailView.as_view(),
        name='thread-detail'),
]

rest_api_urls = [
   re_path(r'^api/get-messages/(?P<thread_id>[0-9]+)/$',
           views.ChatMessageListing.as_view(), name='thread-messages-api'), 
]


urlpatterns += rest_api_urls

app/core/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('chat.urls', namespace='chat')),
]

app/accounts/models.py
from django.db import models

# Create your models here.

app/chat/models.py
from django.db import models
from django.contrib.auth.models import User


class Thread(models.Model):
	creator = models.ForeignKey(User, on_delete=models.CASCADE,
                                related_name='thread_creator')
	thread_name = models.CharField("The name of thread", max_length=120)
	timestamp = models.DateTimeField(auto_now_add=True)


	def __str__(self):
		string = f"Thread: {self.thread_name},\
		User: {self.creator.username}"
		return string


class ChatMessage(models.Model):
    thread_id = models.ForeignKey(Thread, on_delete=models.CASCADE)
    user_id = models.ForeignKey(User, verbose_name='sender', null=True,
    	                        on_delete=models.CASCADE)
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)


    def __str__(self):
    	if len(self.message) > 10:
    		msg = f"{self.message[:11]} ..."
    	else:
    		msg = self.message

    	try:
    		string = f"Thread: {self.thread_id.thread_name},\
    		Message: {msg}, User: {self.user_id.username}"
    	except AttributeError:
    		string = f"Thread: {self.thread_id.thread_name},\
    		Message: {msg}, User: Anonymous"

    	return string

app/accounts/forms.py
from django import forms
from django.contrib.auth import authenticate


class SignInForm(forms.Form):
	username = forms.CharField(max_length=255, required=True)
	password = forms.CharField(widget=forms.PasswordInput, required=True)

	def clean(self):
		username = self.cleaned_data.get('username')
		password = self.cleaned_data.get('password')
		user = authenticate(username=username, password=password)
		if not user or not user.is_active:
			msg = "Sorry, an error occured. Check login and password."
			raise forms.ValidationError(msg)
		return self.cleaned_data

	def login(self, request):
		username = self.cleaned_data.get('username')
		password = self.cleaned_data.get('password')
		user = authenticate(username=username, password=password)
		return user

app/accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, logout
from django.views import View
from django.shortcuts import render, redirect

from .forms import SignInForm



class SignUpView(View):

	def get(self, request):
		context = {}
		context['sign_up_form'] = UserCreationForm()

		return render(request, 'accounts/sign_up.html', context)


	def post(self, request):
		sign_up_form = UserCreationForm(request.POST)

		if sign_up_form.is_valid():
			sign_up_form.save()

			return redirect('accounts:sign-in')

		context = {'sign_up_form': sign_up_form}
		return render(request, 'accounts/sign_up.html', context)



class SignInView(View):

	def get(self, request):
		context = {}
		context['sign_in_form'] = SignInForm()

		return render(request, 'accounts/sign_in.html', context)


	def post(self, request):
		sign_in_form = SignInForm(request.POST)

		if sign_in_form.is_valid():
			user = sign_in_form.login(request)
			if user:
				login(request, user)
				return redirect('chat:thread-list')
    	
		context = {'sign_in_form': sign_in_form}
		return render(request, 'accounts/sign_in.html', context)


def logout_view(request):
    logout(request)
    return redirect('accounts:sign-in')

app/chat/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.http import HttpResponseForbidden
from django.conf import settings

from rest_framework.pagination import PageNumberPagination
from rest_framework import generics

from .models import Thread, ChatMessage
from .serializers import ChatMessagesSerializer


class ThreadListView(View):
	
	def get(self, request):
		context = {

			'thread_list': Thread.objects.all(),
		}

		return render(request, 'chat/thread_list.html', context)

	def post(self, request):
		current_user = request.user
		thread_name = request.POST.get('thread_name')

		new_thread = Thread.objects.create(
			creator=current_user,
			thread_name=thread_name
		)

		return redirect('chat:thread-detail', thread_id=new_thread.id)


class ThreadDetailView(View):

	def get(self, request, thread_id):

		thread_obj = get_object_or_404(Thread, pk=thread_id)
		thread_messages = ChatMessage.objects.filter(thread_id=thread_id)

		context = {
			'thread_obj': thread_obj,
			'thread_messages': thread_messages,
		}

		return render(request, 'chat/thread_detail.html',context)


class ChatMessagesPagination(PageNumberPagination):
    page_size = settings.REST_FRAMEWORK['PAGE_SIZE']


class ChatMessageListing(generics.ListAPIView):
	pagination_class = ChatMessagesPagination
	serializer_class = ChatMessagesSerializer

	http_method_names = ['get']

	def get_queryset(self):
		thread_id = self.kwargs.get('thread_id')
		chat_messages = ChatMessage.objects.filter(thread_id=thread_id).order_by('timestamp')
		return chat_messages

app/accounts/templates/accounts/logout.html
<!DOCTYPE html>
<html>
<head>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'accounts/css/logout.css' %}">

	<link rel="shortcut icon" type="image/jpg" href="https://icons-for-free.com/iconfiles/png/512/talk+icon-1320167913753487880.png"/>

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>

	<title>Discourse</title>
</head>
<body>

<div id='main_text'>
	<h1 class="mt-2">Logout</h1>
	<p>You are logged out!</p>
	<p>You will be rederected on the main page in 5 seconds...</p>
	<div class="spinner-border text-dark" role="status">
	<div class="loader"></div>
  <span class="sr-only">Loading...</span>
</div>
</div>

<script type="text/javascript">
	

	function redirect(){
		let redirect_url = "{% url 'discourse:main' %}"
		window.location.replace(redirect_url);
	}

	setTimeout(redirect, 5000)

</script>
</body>
</html>

app/accounts/templates/accounts/sign_in.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Sign In</title>

</head>
<body>
    <form method="POST" action="">
        {% csrf_token %}
        
        {{sign_in_form.as_p}}

        <input type="submit" value="Sign Up">
    </form>

    {% if sign_in_form.non_field_errors %}
        <ul class='form-errors'>
            {% for error in sign_in_form.non_field_errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}

</body>
</html>

app/accounts/templates/accounts/sign_up.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Sign Up</title>

</head>
<body>
    <form method="POST" action="">
        {% csrf_token %}
        {{ sign_up_form.as_p }}

        <input type="submit" value="Sign Up">
    </form>

</body>
</html>

app/chat/templates/chat/thread_detail.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ thread_obj.thread_name }}</title>

    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/reconnecting-websocket/1.0.0/reconnecting-websocket.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    {% load static %}
    <script src="{% static 'chat/js/helpers.js' %}"></script> 

</head>
<body>
    <h1> {{ thread_obj.thread_name }}</h1>
    <a href="{% url 'chat:thread-list' %}">Back to the list of threads</a>
    <hr>

    <button id='load_more_messages'>Load more messages</button>
    <div style="overflow-y: scroll; height:400px;" id="scrollarea">
        <ul id="chat_items">

        </ul>
    </div>

    <hr>

    {% if request.user.is_authenticated %}
    <form action="" method="POST" id='send_message_form' style="margin-bottom: 1rem;">
        {% csrf_token %}

        <fieldset>
            <legend>Send message</legend>
            
            <div>
                <label for="is_anonymous_message">Send message as anonymous</label>
                <input type="checkbox" id="is_anonymous_message" name="is_anonymous_message" value="off">
            </div>

            <textarea id="textarea_message" name="textarea_message" required minlength="1" rows="2" cols="211" style="resize: vertical;"></textarea><br><br>

            <label for="is_delay">Send message with delay</label>
            <input type="text" placeholder="delay date e.g dd/mm/yyyy" id=delay_date>
            <input type="text" placeholder="delay time e.g hours:minues" id=delay_time>
            
            <input type='submit' value="Send">
        </fieldset>
    <form>



    {% else %}
        <p> To send messages you should be authenticated -> <a href="{% url 'accounts:sign-up' %}">Sign Up</a> | <a href="{% url 'accounts:sign-in'%}">Sign In </a></p>

    {% endif %}


<script>
// Misc
scrollToBottom('scrollarea');

// Message pagination
var url = "{% url 'chat:thread-messages-api' thread_obj.id %}";
var num_of_pages;
var url_of_last_page;

var next_page_url = null;
(async () => {
    num_of_pages =  await getNumOfPages(url);

    if (!num_of_pages)
    {
        $('#load_more_messages').remove();
        return;
    }

    if (num_of_pages > 1)
    {

        if (num_of_pages == 2){
            next_page_url = url;
            url_of_last_page = `${url}?page=${num_of_pages}`
        }
        else
        {
            next_page_url = `${url}?page=${num_of_pages-1}`;
            url_of_last_page = `${url}?page=${num_of_pages}` 
        }
    } else if (num_of_pages == 1)
    {
        url_of_last_page = url;
        $('#load_more_messages').remove();
    }

    var last_page_messages = await getPageMessages(url_of_last_page);
    await insertMessagesFromPage('#chat_items', last_page_messages, 'initial');

    $('#load_more_messages').click(async(e) => {
        num_of_pages--;

        if (next_page_url){
            var page_messages = await getPageMessages(next_page_url);

            if (num_of_pages > 1)
            {
                if (num_of_pages == 2){
                    next_page_url = url;
                }
                else
                {
                    next_page_url = `${url}?page=${num_of_pages-1}`; 
                }
            }
            else if (num_of_pages == 1)
            {
                next_page_url = null;
            }

            await insertMessagesFromPage('#chat_items',page_messages, 'pagination_scrolling_top');
        }

        if (num_of_pages == 1)
        {
            $('#load_more_messages').remove();
        }

    })

})();

// WebSockets
const loc = window.location;

var wsStart = 'ws://';
if (loc == 'https:'){
    wsStart = 'wss://'
}

var endpoint = wsStart + loc.host + loc.pathname;
var socket = new ReconnectingWebSocket(endpoint);

socket.onmessage = function(e){
    var data = JSON.parse(e.data);
    console.log(data);

    var username = data.current_user_username;
    //var timestamp = Date.parse(data.timestamp);
    var timestamp = data.timestamp;
    var message = data.message;

    var msg_template = `
        <li>
            <div id="message">
                <b>${username}</b><br>
                <i>${timestamp}</i><br>

                <p>${message}</p>
            </div>
        </li>
    `;

    $('#chat_items').append(msg_template);

    scrollToBottom('scrollarea');
}

socket.onopen = function(e){

    $('#send_message_form').submit(function(event){
        event.preventDefault();

        var is_anonymous_message = 'not_anonymous';
        if ($('#is_anonymous_message').is(":checked"))
        {
            is_anonymous_message = 'anonymous';
        }

        var message = $('#textarea_message').val();

        var is_delay = 'no_delay';
        var delay_date = $('#delay_date').val();
        var delay_time = $('#delay_time').val();

        if (delay_date && delay_time)
        {
            is_delay = 'delay';
        }

        var data = {
            'current_thread_id': '{{ thread_obj.id }}',
            'current_user_id': '{{ request.user.id }}',
            'current_user_username':'{{ request.user.username }}',
            'is_anonymous_message': is_anonymous_message,
            'message': message,
            'is_delay': is_delay,
            'delay_date': delay_date,
            'delay_time': delay_time 
        };

        // Clears input field
        $('#textarea_message').val("");

        socket.send(JSON.stringify(data));

    })        
}

socket.onerror = function(e){
    console.log("error", e);
}

socket.onclose = function(e){
    console.log("close connection", e);
}
    
</script>
</body>
</html>

app/chat/templates/chat/thread_list.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Threads</title>

</head>
<body>

    {% if request.user.is_authenticated %}
        <form action="" method="POST">
            {% csrf_token %}
            <label for="thread_name">Thread name: </label><br>
            <input type="text" name="thread_name" id="thread_name">
            <input type="submit" value="Create new thread">
        </form>

    <hr>
    {% endif %}

    <h1> The list of threads: </h1>

    {% if thread_list%}
        <ul>
            {% for thread in thread_list%}
                <li> <a href="{% url 'chat:thread-detail' thread.id %}">{{ thread.thread_name }} | Creator: {{ thread.creator.username }}</li>
            {% endfor %}

        </ul>
    {% endif %}

</body>
</html>